use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;
use wasm_bindgen::prelude::*;

/// External platform that originates video content.
#[wasm_bindgen]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum SourcePlatform {
    Zoom,
    Loom,
    Fireflies,
    YouTube,
    /// Direct uploads to Kaltura (often live-streamed via OBS/Streamyard
    /// to Kaltura's RTMP ingest, then captured as VOD).
    Kaltura,
    /// Shorts generated by Opus Clip from a parent recording. Not a
    /// "true" source in the ingest-pipeline sense — the clip is a
    /// derivative — but modelled as its own source_platform so each
    /// clip is a first-class catalog row with a ClipOf upstream_link
    /// back to the parent (ADR-055).
    OpusClip,
    /// Video files ingested from Google Drive — either a public share
    /// pasted by a contributor OR an authenticated pull triggered by a
    /// Publisher via ADR-042's OAuth vault. Bytes are streamed to the
    /// FUSE bucket at import time (ADR-071 §3) so the record is
    /// durable against the Drive share being revoked.
    GoogleDrive,
}

/// Any platform a video can exist on (source or destination).
#[wasm_bindgen]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Platform {
    Zoom,
    Loom,
    Fireflies,
    YouTube,
    Kaltura,
    Veedio,
    OpusClip,
    GoogleDrive,
}

impl From<SourcePlatform> for Platform {
    fn from(sp: SourcePlatform) -> Self {
        match sp {
            SourcePlatform::Zoom => Platform::Zoom,
            SourcePlatform::Loom => Platform::Loom,
            SourcePlatform::Fireflies => Platform::Fireflies,
            SourcePlatform::YouTube => Platform::YouTube,
            SourcePlatform::Kaltura => Platform::Kaltura,
            SourcePlatform::OpusClip => Platform::OpusClip,
            SourcePlatform::GoogleDrive => Platform::GoogleDrive,
        }
    }
}

impl Platform {
    /// Lowercase prefix that import flows prepend to external IDs to
    /// guarantee catalog-wide uniqueness of `source_id`. Used by
    /// `normalize_external_id` for cross-role duplicate detection
    /// (ADR-049 slice 1) so an Origin location with `youtube-WQov…`
    /// and a Destination location with `WQov…` are recognised as the
    /// same YouTube video, not two distinct entries.
    pub fn id_prefix(self) -> &'static str {
        match self {
            Platform::Zoom => "zoom-",
            Platform::Loom => "loom-",
            Platform::Fireflies => "fireflies-",
            Platform::YouTube => "youtube-",
            Platform::Kaltura => "kaltura-",
            Platform::Veedio => "veedio-",
            Platform::OpusClip => "opusclip-",
            Platform::GoogleDrive => "drive-",
        }
    }

    /// Strip the `<platform>-` prefix from an external_id so the
    /// underlying platform-native ID can be compared regardless of
    /// which import path produced the entry. ADR-049 slice 1.
    pub fn normalize_external_id<'a>(self, id: &'a str) -> &'a str {
        let prefix = self.id_prefix();
        id.strip_prefix(prefix).unwrap_or(id)
    }
}

/// Role of a platform location in the video lifecycle.
#[wasm_bindgen]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum LocationRole {
    Origin,
    Intermediate,
    Destination,
}

/// A platform where this video exists, with its external identity.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PlatformLocation {
    pub platform: Platform,
    pub external_id: String,
    pub external_url: Option<String>,
    pub role: LocationRole,
    #[serde(default)]
    pub ordinal: u32,
    pub synced_at: DateTime<Utc>,
    #[serde(default)]
    pub status: Option<String>,
}

/// ADR-077 §1 — how far one declared destination got.
///
/// `Skipped` is for a destination the operator removed at publish time
/// (ADR-075's per-record override) — declared by the series but
/// deliberately not attempted for this record, which is different from
/// `Failed`.
#[wasm_bindgen]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum OutcomeState {
    Pending,
    Pushed,
    Failed,
    Skipped,
}

/// ADR-077 §1 — the per-destination outcome the aggregate was missing.
///
/// One of these exists per destination the series declared, so the
/// record can answer "declared three, two attempted, one landed, and
/// here is the visibility each actually has" — which nothing could
/// answer while `destination_id` / `destination_url` were scalars.
///
/// `declared_visibility` and `observed_visibility` are deliberately
/// separate and deliberately `String`, not an enum: each platform has
/// its own vocabulary (YouTube public/unlisted/private, Kaltura
/// public/members/unlisted, Drive share scopes) and forcing them
/// through one enum is how the YouTube-shaped `privacy_status` ended up
/// standing in for all three.
///
/// The pair also encodes the gap ADR-077 §5 closes: today only YouTube
/// applies its declared visibility at push time, so for Kaltura and
/// Drive `declared_visibility` is what was asked for and
/// `observed_visibility` stays `None` until a read-back exists.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct DestinationOutcome {
    pub platform: Platform,
    /// What the series asked for, in the platform's own vocabulary.
    #[serde(default)]
    pub declared_visibility: Option<String>,
    pub state: OutcomeState,
    /// Platform-native id once pushed (YouTube video id, Kaltura entry
    /// id, Drive file id).
    #[serde(default)]
    pub external_id: Option<String>,
    #[serde(default)]
    pub external_url: Option<String>,
    #[serde(default)]
    pub pushed_at: Option<DateTime<Utc>>,
    /// Last visibility actually read back from the platform (ADR-077 §5).
    #[serde(default)]
    pub observed_visibility: Option<String>,
    #[serde(default)]
    pub observed_at: Option<DateTime<Utc>>,
    /// Failure detail when `state` is `Failed`.
    #[serde(default)]
    pub error: Option<String>,
}

impl DestinationOutcome {
    /// A freshly declared, not-yet-attempted destination.
    pub fn pending(platform: Platform, declared_visibility: Option<String>) -> Self {
        Self {
            platform,
            declared_visibility,
            state: OutcomeState::Pending,
            external_id: None,
            external_url: None,
            pushed_at: None,
            observed_visibility: None,
            observed_at: None,
            error: None,
        }
    }
}

/// Lifecycle status of a video within the curation pipeline.
#[wasm_bindgen]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum VideoStatus {
    Discovered,
    InScope,
    Approved,
    Skipped,
    Publishing,
    Published,
    Failed,
    Abandoned,
    ToRetry,
}

impl VideoStatus {
    /// Returns true if this status can transition to `InScope`.
    pub fn can_scope(&self) -> bool {
        matches!(self, VideoStatus::Discovered)
    }

    /// Returns true if this status can transition to `Approved`.
    pub fn can_approve(&self) -> bool {
        matches!(
            self,
            VideoStatus::Discovered | VideoStatus::InScope | VideoStatus::Skipped | VideoStatus::Failed | VideoStatus::ToRetry
        )
    }

    /// Returns true if this status can transition to `Skipped`.
    pub fn can_skip(&self) -> bool {
        matches!(self, VideoStatus::Discovered | VideoStatus::InScope)
    }

    /// Returns true if this status can transition to `Publishing`.
    pub fn can_publish(&self) -> bool {
        matches!(self, VideoStatus::Approved)
    }

    /// Returns true if this status can transition to `Abandoned`.
    pub fn can_abandon(&self) -> bool {
        matches!(
            self,
            VideoStatus::Failed | VideoStatus::InScope | VideoStatus::Discovered | VideoStatus::Skipped | VideoStatus::Published
        )
    }

    /// Returns true if this status can transition to `ToRetry`.
    pub fn can_mark_to_retry(&self) -> bool {
        matches!(self, VideoStatus::Failed | VideoStatus::Published)
    }
}

/// User role within the system.
#[wasm_bindgen]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum UserRole {
    Admin,
    Publisher,
    Viewer,
}

/// How a downstream VideoRecord relates to its upstream source.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum DerivationType {
    /// Different platform capture of the same meeting/session.
    SameEvent,
    /// Transcript produced by processing the upstream video.
    TranscribedFrom,
    /// Screen-recording or re-stream of the upstream.
    ScreenRecordingOf,
    /// Time-bounded clip extracted from the upstream.
    ClipOf,
    /// ADR-049: this record is a live-broadcast destination of the
    /// upstream (e.g. a YouTube Live record whose RTMP source was a
    /// Zoom call, often via Restream/StreamYard). Directional — the
    /// upstream is the producing source, this record is where it was
    /// broadcast. Distinct from `SameEvent` which is peer-to-peer.
    BroadcastedFrom,
}

/// Whether a provenance link was established automatically or by a curator.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum LinkOrigin {
    Auto,
    Manual,
}

/// A directional link from this VideoRecord to an upstream source.
/// `video_id` is None when the upstream is a phantom (not indexed in this catalog).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct UpstreamLink {
    /// Catalog ID of the upstream VideoRecord, if present.
    pub video_id: Option<Uuid>,
    pub platform: Platform,
    pub external_id: String,
    /// Display hint for the platform account (e.g. "ruv@ruv.net"). Not a foreign key.
    pub account_hint: Option<String>,
    pub relation: DerivationType,
    pub linked_by: LinkOrigin,
    pub linked_at: DateTime<Utc>,
}

/// A provenance link the curator has explicitly rejected — prevents re-suggestion.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RejectedLink {
    pub platform: Platform,
    pub external_id: String,
    pub rejected_at: DateTime<Utc>,
}

/// Internal annotation attached to a video by a curator, owner, or moderator.
/// Not published to destination platforms.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Note {
    pub id: Uuid,
    pub author_id: Uuid,
    pub text: String,
    pub created_at: DateTime<Utc>,
}

impl Note {
    pub fn new(author_id: Uuid, text: String) -> Self {
        Self {
            id: Uuid::new_v4(),
            author_id,
            text,
            created_at: Utc::now(),
        }
    }
}

/// Per-record summary indicator counts surfaced as M:NN L:NN T:NN C:NN
/// in the Overview lozenge (ADR-046). Populated when a summary is
/// generated by counting bullets under each structured section heading.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct SummaryCounts {
    /// Key Moments — narrative beats in the video.
    pub m: u32,
    /// Key Learnings — generalisable insights.
    pub l: u32,
    /// Key Takeaways — action items.
    pub t: u32,
    /// Chat-Sparked Discussions — moments where embedded chat showed engagement.
    pub c: u32,
}

/// Identity of the user performing a command, used for authorization checks.
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub struct Actor {
    pub user_id: Uuid,
    pub role: UserRole,
}

impl Actor {
    pub fn new(user_id: Uuid, role: UserRole) -> Self {
        Self { user_id, role }
    }

    pub fn is_admin(&self) -> bool {
        self.role == UserRole::Admin
    }

    pub fn is_publisher(&self) -> bool {
        self.role == UserRole::Publisher
    }

    pub fn is_admin_or_publisher(&self) -> bool {
        self.is_admin() || self.is_publisher()
    }
}

/// Full-text search query with filters.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SearchQuery {
    pub text: String,
    pub source_filter: Option<SourcePlatform>,
    pub status_filter: Option<VideoStatus>,
    pub owner_filter: Option<Uuid>,
    pub date_from: Option<DateTime<Utc>>,
    pub date_to: Option<DateTime<Utc>>,
    pub participant: Option<String>,
    pub page: u32,
    pub page_size: u32,
}

impl SearchQuery {
    pub fn new(text: String) -> Self {
        Self {
            text,
            page: 1,
            page_size: 20,
            ..Default::default()
        }
    }
}
