/**
 * ADR-064 — convert Show Notes Google Doc markdown into a plain-text
 * YouTube-description-compatible string.
 *
 * YouTube's description field is plain text (no markdown rendering)
 * with two special affordances:
 *   - Lines whose first token is HH:MM:SS become clickable chapter
 *     jumps in the player, PROVIDED
 *       * the FIRST such line has timestamp 00:00:00,
 *       * timestamps are strictly increasing, AND
 *       * there are at least 3 chapter lines.
 *     Any rule violation and YouTube ignores the whole chapter list.
 *   - URLs autolinkify.
 *
 * Our Show Notes emit `- [HH:MM:SS] Text` bullets under `### Key Moments`
 * and friends. We rewrite each qualifying bullet into a bare
 * `HH:MM:SS Text` line so YouTube picks up chapter cues, then strip
 * remaining markdown (headings, bold, italic) that would appear as
 * literal characters.
 *
 * Fully deterministic — no LLM call.
 */

const MAX_YOUTUBE_DESCRIPTION_CHARS = 5000;

// Match "[H:MM:SS]", "[HH:MM:SS]", "[MM:SS]", "[M:SS]" at line start
// after an optional bullet marker.
const BULLET_TS_RE = /^(\s*)(?:[-*+]|\d+\.)\s+\[(\d{1,2}):(\d{2})(?::(\d{2}))?\]\s*/;

function pad2(n: number): string {
  return n < 10 ? `0${n}` : String(n);
}

function tsToSeconds(ts: string): number {
  const parts = ts.split(":").map(Number);
  if (parts.length === 3) return parts[0] * 3600 + parts[1] * 60 + parts[2];
  if (parts.length === 2) return parts[0] * 60 + parts[1];
  return 0;
}

export function showNotesToDescription(md: string): string {
  if (!md) return "";

  // 1. Strip the auto-generated banner ("🤖 Generated by video-sync
  //    summary-prompt vN on <iso>… \n---\n").
  let text = md.replace(/^🤖 Generated by video-sync summary-prompt[\s\S]*?---\s*/m, "").trim();

  // 1a. Google Docs' text/markdown export escapes special characters
  //     with backslashes: `\[`, `\]`, `\.`, `\-`, `\*`, `\(`, `\)`,
  //     `\!`, `\_`, `\<`, `\>`, `\|`. Those escapes are literal to
  //     YouTube's plain-text description — a bullet like
  //     `* \[00:00:00\] Piotr` reads as `* \[00:00:00\] Piotr` on
  //     YouTube and also causes our BULLET_TS_RE below to miss the
  //     timestamp entirely. Un-escape before doing anything else.
  //     The character list matches the escapes Google's exporter
  //     actually emits; adding others is safe.
  text = text.replace(/\\([\[\]().\-*_<>|!`])/g, "$1");

  // 1b. Kill "chapter map" prose lines: any line that carries 3+
  //     `HH:MM:SS` timestamps inline is either a comma/space-joined
  //     TOC ("00:00 Intro 05:30 CloudFlow 20:15 Traceability…") or a
  //     model artifact. YouTube's chapter picker needs one cue per
  //     line — a merged line is worse than useless. The real cues
  //     will come from the M/L/T/C bullets we rewrite below.
  const TS_INLINE = /\b\d{1,2}:\d{2}(?::\d{2})?\b/g;
  text = text.split("\n").filter((ln) => {
    const trimmed = ln.trim();
    if (!trimmed) return true;
    const bulletMatch = trimmed.match(/^(?:[-*+]|\d+\.)\s+/);
    if (bulletMatch) return true;
    const timestampCount = (trimmed.match(TS_INLINE) ?? []).length;
    return timestampCount < 3;
  }).join("\n");

  // 2. Line-by-line rewrite. We build two pieces in parallel:
  //    - a "chapters" list of {seconds, line} tuples so we can validate
  //      YouTube's constraints (first at 0, monotone increasing, ≥3)
  //    - the flattened body lines with markdown stripped
  const lines = text.split("\n");
  const bodyLines: string[] = [];
  interface Chapter { seconds: number; line: string; idxInBody: number; }
  const chapters: Chapter[] = [];

  for (const raw of lines) {
    const bulletMatch = raw.match(BULLET_TS_RE);
    if (bulletMatch) {
      const [, , h, m, s] = bulletMatch;
      // Chapter form: pad hour/minute/second correctly. When no
      // seconds group, treat "[MM:SS]" as minutes/seconds.
      const hourNum = s !== undefined ? Number(h) : 0;
      const minNum  = s !== undefined ? Number(m) : Number(h);
      const secNum  = s !== undefined ? Number(s) : Number(m);
      const ts = `${pad2(hourNum)}:${pad2(minNum)}:${pad2(secNum)}`;
      const rest = raw.slice(bulletMatch[0].length).trim();
      const chapterLine = `${ts} ${rest}`;
      chapters.push({ seconds: tsToSeconds(ts), line: chapterLine, idxInBody: bodyLines.length });
      bodyLines.push(chapterLine);
      continue;
    }

    // Non-bullet lines: strip markdown formatting.
    let out = raw;
    // Headings: "## Title" → "Title"
    out = out.replace(/^\s{0,3}#{1,6}\s+/, "");
    // Bullets that aren't chapter-style: leave the leading dash for
    // paragraph rhythm, but strip `**` / `_` / backticks.
    out = out.replace(/\*\*(.+?)\*\*/g, "$1");
    out = out.replace(/(^|[\s(])\*(.+?)\*(?=$|[\s.,;:!?)])/g, "$1$2");
    out = out.replace(/(^|[\s(])_([^_]+)_(?=$|[\s.,;:!?)])/g, "$1$2");
    out = out.replace(/`([^`]+)`/g, "$1");
    // Blockquote markers.
    out = out.replace(/^\s{0,3}>\s*/, "");
    bodyLines.push(out);
  }

  // 3. Validate YouTube chapter rules. If violated, we still keep the
  //    bare "HH:MM:SS Text" lines in the body (they read fine as
  //    plain text) — YouTube just won't render them as clickable
  //    chapter jumps. If violated only by "first isn't 00:00:00",
  //    prepend a synthetic "00:00:00 Opening" so cues DO fire.
  const monotone = chapters.every((c, i) => i === 0 || c.seconds > chapters[i - 1].seconds);
  const enoughChapters = chapters.length >= 3;
  const firstIsZero = chapters.length > 0 && chapters[0].seconds === 0;
  if (enoughChapters && monotone && !firstIsZero) {
    // Prepend a synthetic opener before the first chapter line in the body.
    const insertAt = chapters[0].idxInBody;
    bodyLines.splice(insertAt, 0, "00:00:00 Opening");
  }

  // 4. Collapse runs of 3+ blank lines to a single blank line.
  const collapsed: string[] = [];
  let blankStreak = 0;
  for (const ln of bodyLines) {
    if (ln.trim() === "") {
      blankStreak++;
      if (blankStreak <= 1) collapsed.push("");
    } else {
      blankStreak = 0;
      collapsed.push(ln.trimEnd());
    }
  }

  // 5. Enforce YouTube's 5000-char cap. Truncate at the last full
  //    line under the limit, append an ellipsis marker.
  let out = collapsed.join("\n").trim();
  if (out.length > MAX_YOUTUBE_DESCRIPTION_CHARS) {
    const clip = out.slice(0, MAX_YOUTUBE_DESCRIPTION_CHARS - 20);
    const lastNewline = clip.lastIndexOf("\n");
    out = (lastNewline > 0 ? clip.slice(0, lastNewline) : clip) + "\n…";
  }
  return out;
}

