#!/usr/bin/env bash
#
# One-time setup for ADR-036 Google Workspace authentication.
#
# Creates the three Workspace groups, configures Identity-Aware Proxy on
# the Cloud Run service, and prints the IAP_AUDIENCE value to add to
# deploy.sh as an env var.
#
# Requires: gcloud authenticated as a project owner with Workspace admin
# access for agentics.org. If you lack one, route this to your GWS admin.
#
#   bash scripts/iap-setup.sh
#
# Idempotent: re-runs are safe. The Workspace group creation step is
# skipped if the group already exists.

set -euo pipefail

PROJECT_ID="${PROJECT_ID:-agentics-487016}"
REGION="${REGION:-us-central1}"
SERVICE="${SERVICE:-video-sync}"
DOMAIN="${DOMAIN:-agentics.org}"

KEY_ADMIN_GROUP="video-sync-key-admins@${DOMAIN}"
OPERATOR_GROUP="video-sync-operators@${DOMAIN}"
VIEWER_GROUP="video-sync-viewers@${DOMAIN}"

echo "==> Project: ${PROJECT_ID}"
echo "==> Region:  ${REGION}"
echo "==> Service: ${SERVICE}"
echo "==> Domain:  ${DOMAIN}"
echo

# 1. Enable IAP + Cloud Identity APIs
# Cloud Identity is required for `gcloud identity groups create` below
# (QE finding rev#10).
echo "==> Enabling IAP + Cloud Identity APIs"
gcloud services enable \
  iap.googleapis.com \
  cloudidentity.googleapis.com \
  --project="${PROJECT_ID}" || {
  echo "  (skipped — likely missing serviceusage.serviceUsageAdmin)"
  echo "  Verify: gcloud services list --enabled --project=${PROJECT_ID} | grep -E 'iap|cloudidentity'"
}

# 2. Create Workspace groups via Cloud Identity API
# (gcloud identity groups requires the Cloud Identity API and admin perms)
echo "==> Creating Workspace groups (requires Workspace admin)"
for group_email in "${KEY_ADMIN_GROUP}" "${OPERATOR_GROUP}" "${VIEWER_GROUP}"; do
  display_name="$(echo "${group_email}" | cut -d@ -f1)"
  if gcloud identity groups describe "${group_email}" >/dev/null 2>&1; then
    echo "  ${group_email} already exists"
  else
    gcloud identity groups create "${group_email}" \
      --organization="${DOMAIN}" \
      --display-name="${display_name}" \
      --description="Video Sync ${display_name}" \
      || echo "  !! create ${group_email} failed — request from Workspace admin"
  fi
done

# 3. Bind groups to Cloud Run Invoker so anyone in any of the three can
#    reach the service. In-app role check distinguishes capabilities.
echo "==> Granting Cloud Run Invoker to the three groups"
for group_email in "${KEY_ADMIN_GROUP}" "${OPERATOR_GROUP}" "${VIEWER_GROUP}"; do
  gcloud run services add-iam-policy-binding "${SERVICE}" \
    --region="${REGION}" \
    --project="${PROJECT_ID}" \
    --member="group:${group_email}" \
    --role="roles/run.invoker" \
    || echo "  !! grant for ${group_email} failed"
done

# 4. Enable IAP on the Cloud Run service. This is the step that
#    actually puts a Google sign-in wall in front of browser requests
#    AND injects the X-Goog-IAP-JWT-Assertion header that auth.ts
#    validates. Without it, --no-allow-unauthenticated just means
#    "must present a Google identity token" — useful for service-to-
#    service calls but not for browser users.
echo "==> Enabling IAP on the Cloud Run service"
gcloud beta run services update "${SERVICE}" \
  --region="${REGION}" \
  --project="${PROJECT_ID}" \
  --iap \
  || {
    echo
    echo "  !! IAP enable failed. Common causes:"
    echo "     - Missing roles/iap.admin (or owner/editor) on your account"
    echo "     - OAuth consent screen / IAP brand not yet configured for the project"
    echo "       (set up in Cloud Console → APIs & Services → OAuth consent screen)"
    echo "     - 'beta' component missing: gcloud components install beta"
    echo
    echo "  The earlier steps still applied. You can re-run this script after"
    echo "  resolving the blocker; it's idempotent."
    exit 1
  }

# 5. Remove the public-access IAM binding (allUsers → run.invoker).
#    The `--no-allow-unauthenticated` flag on `gcloud run services update`
#    is unsupported in some gcloud versions; using IAM directly is
#    portable and idempotent.
echo "==> Removing public access (allUsers run.invoker binding)"
gcloud run services remove-iam-policy-binding "${SERVICE}" \
  --region="${REGION}" \
  --project="${PROJECT_ID}" \
  --member="allUsers" \
  --role="roles/run.invoker" \
  --quiet \
  || echo "  (allUsers binding already absent — fine)"

# 6. Compute the IAP_AUDIENCE for the JWT verifier. The Cloud Run IAP
#    audience format is /projects/<num>/global/backendServices/<id>
#    where the id is generated by IAP when it wraps the service. Read
#    it back from the service's IAP config.
PROJECT_NUMBER=$(gcloud projects describe "${PROJECT_ID}" --format='value(projectNumber)')
IAP_BACKEND_ID=$(gcloud run services describe "${SERVICE}" \
  --region="${REGION}" \
  --project="${PROJECT_ID}" \
  --format='value(spec.template.metadata.annotations."run.googleapis.com/iap-id")' 2>/dev/null || true)
if [[ -z "${IAP_BACKEND_ID}" ]]; then
  # Fallback: older gcloud put the id elsewhere; service uid often matches
  # for the direct-Cloud-Run IAP setup
  IAP_BACKEND_ID=$(gcloud run services describe "${SERVICE}" --region="${REGION}" --project="${PROJECT_ID}" --format='value(metadata.uid)')
  echo "  (note: IAP backend id read from metadata.uid as fallback)"
fi
IAP_AUDIENCE="/projects/${PROJECT_NUMBER}/global/backendServices/${IAP_BACKEND_ID}"

echo
echo "=========================================================="
echo "IAP setup complete."
echo
echo "Next step — deploy in IAP mode:"
echo
echo "  export IAP_AUDIENCE='${IAP_AUDIENCE}'"
echo "  bash deploy.sh"
echo
echo "Role assignment in IAP mode:"
echo "  - WS_DOMAIN unset (default): use KEY_ADMIN_EMAILS / OPERATOR_EMAILS"
echo "    / VIEWER_EMAILS env vars (already defaulted in deploy.sh)."
echo "  - WS_DOMAIN=${DOMAIN}: query Cloud Identity for group membership."
echo "    Requires the runtime SA to be a Manager on each group."
echo "    Add via Workspace Admin → Groups → [each group] → Settings →"
echo "    Group managers: ${PROJECT_NUMBER}-compute@developer.gserviceaccount.com"
echo "=========================================================="
