#!/usr/bin/env bash
#
# Reclaim disk space by pruning build artifacts and caches (ADR-038).
#
# Usage:
#   bash scripts/prune-build-artifacts.sh           # dry-run, safe level
#   bash scripts/prune-build-artifacts.sh --apply   # actually delete (safe)
#   bash scripts/prune-build-artifacts.sh --apply --aggressive
#   bash scripts/prune-build-artifacts.sh --apply --nuclear
#
# Levels:
#   safe       — Next .next/, dist/, build artefacts that regenerate fast
#   aggressive — + Docker images and builder cache (slows next build)
#   nuclear    — + node_modules and Rust target/ (full reinstall on next run)
#
# Never touches:
#   data/                   — server-side persistent state (ADR-018)
#   .git, .gitignore        — version control
#   src/, web/src/, docs/   — source code
#   any *.json under data/  — server state files

set -euo pipefail

APPLY=0
LEVEL="safe"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --apply) APPLY=1; shift ;;
    --aggressive) LEVEL="aggressive"; shift ;;
    --nuclear) LEVEL="nuclear"; shift ;;
    -h|--help)
      sed -n '2,/^$/p' "$0" | sed 's/^# \?//'
      exit 0
      ;;
    *)
      echo "Unknown arg: $1" >&2
      exit 1
      ;;
  esac
done

cd "$(dirname "$0")/.."
ROOT="$(pwd)"

# ── Helpers ──────────────────────────────────────────────────────────

before_kb() {
  df -k . | awk 'NR==2 {print $4}'
}

human() {
  numfmt --to=iec --suffix=B "$1" 2>/dev/null || echo "${1}B"
}

run() {
  if [[ $APPLY -eq 1 ]]; then
    echo "  $*"
    eval "$*"
  else
    echo "  [dry-run] $*"
  fi
}

size_of() {
  if [[ -e "$1" ]]; then
    du -sh "$1" 2>/dev/null | awk '{print $1}'
  else
    echo "—"
  fi
}

START_FREE_KB=$(before_kb)
echo "==> Before: $(human $((START_FREE_KB * 1024))) free on $(df -h . | awk 'NR==2 {print $6}')"
echo "==> Mode:   $([[ $APPLY -eq 1 ]] && echo APPLY || echo DRY-RUN), level=$LEVEL"
echo

# ── Safe level ───────────────────────────────────────────────────────

echo "── Safe-level targets ──"

# Next.js build output
NEXT_DIR="$ROOT/web/.next"
echo "  web/.next/                         $(size_of "$NEXT_DIR")"
[[ -d "$NEXT_DIR" ]] && run "rm -rf '$NEXT_DIR'"

# tsconfig build info
TSBUILDINFO="$ROOT/web/tsconfig.tsbuildinfo"
echo "  web/tsconfig.tsbuildinfo           $(size_of "$TSBUILDINFO")"
[[ -f "$TSBUILDINFO" ]] && run "rm -f '$TSBUILDINFO'"

# Stray musl SWC binary on glibc systems (.npmrc usually prevents this,
# but historic node_modules trees may still have it)
MUSL="$ROOT/web/node_modules/@next/swc-linux-x64-musl"
echo "  @next/swc-linux-x64-musl (Alpine)  $(size_of "$MUSL")"
[[ -d "$MUSL" ]] && run "rm -rf '$MUSL'"

# .claude-flow trend cache regenerates on next agent run
TRENDCACHE="$ROOT/.claude-flow/.trend-cache.json"
[[ -f "$TRENDCACHE" ]] && {
  echo "  .claude-flow/.trend-cache.json     $(size_of "$TRENDCACHE")"
  run "rm -f '$TRENDCACHE'"
}

# pkg/ — built WASM artefacts, regenerated by wasm-pack
PKG="$ROOT/pkg"
[[ -d "$PKG" ]] && {
  echo "  pkg/ (wasm artefacts)              $(size_of "$PKG")"
  run "rm -rf '$PKG'"
}

# ── Aggressive level ─────────────────────────────────────────────────

if [[ "$LEVEL" == "aggressive" || "$LEVEL" == "nuclear" ]]; then
  echo
  echo "── Aggressive-level targets ──"

  if command -v docker >/dev/null 2>&1; then
    DOCKER_IMG_SIZE=$(docker system df --format '{{.Size}}' 2>/dev/null | head -1 || echo "?")
    echo "  Docker images + build cache        $DOCKER_IMG_SIZE"
    run "docker image prune -a -f"
    run "docker builder prune -a -f"
  else
    echo "  (no docker on PATH)"
  fi
fi

# ── Nuclear level ────────────────────────────────────────────────────

if [[ "$LEVEL" == "nuclear" ]]; then
  echo
  echo "── Nuclear-level targets ──"

  NODE_MODULES="$ROOT/web/node_modules"
  echo "  web/node_modules/                  $(size_of "$NODE_MODULES")"
  [[ -d "$NODE_MODULES" ]] && run "rm -rf '$NODE_MODULES'"

  TARGET="$ROOT/target"
  echo "  target/ (Rust build)               $(size_of "$TARGET")"
  [[ -d "$TARGET" ]] && run "rm -rf '$TARGET'"

  echo
  echo "  After nuclear, you'll need to:"
  echo "    cd web && npm ci"
  echo "    wasm-pack build --target web --out-dir pkg"
fi

# ── Summary ─────────────────────────────────────────────────────────

echo
END_FREE_KB=$(before_kb)
DIFF_KB=$((END_FREE_KB - START_FREE_KB))
echo "==> After:  $(human $((END_FREE_KB * 1024))) free"
if [[ $APPLY -eq 1 && $DIFF_KB -gt 0 ]]; then
  echo "==> Reclaimed: $(human $((DIFF_KB * 1024)))"
elif [[ $APPLY -eq 0 ]]; then
  echo "==> (dry-run; no files removed; re-run with --apply to actually delete)"
fi
